### ISSUE TITLE
Topics that don't exist in both languages

### ISSUE THREAD

**Issue by shingtaklam1324** [rochacbruno/py2rs#24]
Reading through the document, I noticed (particularly in Rust) use of language features that aren't explained and code examples for the other language aren't trivial.

# Examples
- Rust macros
- Rust Implicit returns

**Comment by rochacbruno** [comment]
Do you have a suggestion on how to explain that? can you send a Pull Request?

**Comment by shingtaklam1324** [comment]
I was thinking about doing code examples i. Rust for those, but it wouldn't fit the purpose of this repo as it has no Py equivalent.

Another would be just to add comments when thos features are used, just to explain them, at least for the first time it is used
