### ISSUE TITLE
Some suggestion

### ISSUE THREAD

**Issue by bobogei81123** [rochacbruno/py2rs#4]
1. Aren't Crossbeam and Rayon libraries about threads? They doesn't seem to match the description "Run external commands".

2. The python code of `derive_new` crate `__init__(self, value='default')` kind of suggest that rust has optional parameters, which rust does not.

**Comment by rochacbruno** [comment]
1) I'll dig more into Crossbeam and Rayon and also try to find the `external command runner` equivalent, thanks

2) about derive_new, it offers default values for initializers just like in Python's `__init__` method.

```rust
use std::marker::PhantomData;

#[derive(new)]
struct Generic<'a, T: Default, P> {
    x: &'a str,
    y: PhantomData<P>,
    #[new(default)]
    z: T,
}

let _ = Generic::<i32, u8>::new("Hello");
```

If you have suggestion to replace Rayon and Crossbeam on the list or better description to derive_new please send a Pull Request!

**Comment by rochacbruno** [comment]
1 is fixed!

**Comment by bobogei81123** [comment]
For 2. I meant someone might though
```rust
#[derive(new)]
struct Foo {
    #[new(value = "default")]
    value: String,
}

Foo::new();
Foo::new("bar");
```
would work, since python supports optional argument.

It's not a big problem at all, just a small suggestion.
So I think it's up to you, who is the owner of this awesome list, to decide whether to change it or not.

**Comment by Aofzazgithub** [comment]
What
