### ISSUE TITLE
Wrong library in listing

### ISSUE THREAD

**Issue by diogobaeder** [rochacbruno/py2rs#6]
Great job, Bruno! Nice to know you're into Rust now - I'm barely starting to learn it :-)

So, one issue I found in the listing of libraries is the mention for `mockito`; now, although the homonimous Java library is indeed a proper general mocking library, Rust's `mockito` only really mocks HTTP services, and not structs or methods. Which is a bit sad - I expected more from that library when I saw that name.

Therefore I think it should not be in the list as a Rust alternative to Python's `mock` library - which is a general-purpose mocking library (now integrated into Python 3).

Cheers!
Diogo

**Comment by rochacbruno** [comment]
Thanks @diogobaeder I'll try to find a proper `mocking` library for Rust and replace there.
